version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - cd backend
      - npm install
  build:
    commands:
      - npm run build
      - zip -r function.zip .
      - aws s3 cp function.zip s3://your-bucket-name/function.zip
      - aws lambda update-function-code --function-name MyLambdaFunction --s3-bucket your-bucket-name --s3-key function.zip
artifacts:
  files:
    - function.zip
cache:
  paths:
    - backend/node_modules/**/*
